# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dqset_seed <- function(seed) {
    invisible(.Call(`_dqrng_dqset_seed`, seed))
}

dqset_seed_vector <- function(seed_vec) {
    invisible(.Call(`_dqrng_dqset_seed_vector`, seed_vec))
}

dqset_create_seed_vectors <- function(nseeds, nwords) {
    .Call(`_dqrng_dqset_create_seed_vectors`, nseeds, nwords)
}

#' @rdname dqrng-functions
#' @export
dqRNGkind <- function(kind, normal_kind = "ignored") {
    invisible(.Call(`_dqrng_dqRNGkind`, kind, normal_kind))
}

#' @rdname dqrng-functions
#' @export
dqrunif <- function(n, min = 0.0, max = 1.0) {
    .Call(`_dqrng_dqrunif`, n, min, max)
}

#' @rdname dqrng-functions
#' @export
dqrnorm <- function(n, mean = 0.0, sd = 1.0) {
    .Call(`_dqrng_dqrnorm`, n, mean, sd)
}

#' @rdname dqrng-functions
#' @export
dqrexp <- function(n, rate = 1.0) {
    .Call(`_dqrng_dqrexp`, n, rate)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_dqrng_RcppExport_registerCCallable', PACKAGE = 'dqrng')
})
